const express=require('express');
const {db,setting}=require('../db');
const {requireRole}=require('../security');
const {audit}=require('../services/audit');
const {claimPickup,getPickup,transitionPickup}=require('../services/pickups');
const router=express.Router();
router.use(requireRole('collector'));

router.get('/',(req,res)=>{
  const id=req.session.user.id,profile=db.prepare('SELECT * FROM collector_profiles WHERE user_id=?').get(id);
  const metrics={today:db.prepare("SELECT COUNT(*) c FROM pickup_requests WHERE assigned_collector_id=? AND date(COALESCE(accepted_at,requested_at))=date('now')").get(id).c,active:db.prepare("SELECT COUNT(*) c FROM pickup_requests WHERE assigned_collector_id=? AND status IN ('assigned','accepted','en_route','arrived','collected','delivered')").get(id).c,completed:db.prepare("SELECT COUNT(*) c FROM pickup_requests WHERE assigned_collector_id=? AND status='completed'").get(id).c,weight:Number(db.prepare("SELECT COALESCE(SUM(COALESCE(verified_weight,collected_weight,0)),0) v FROM pickup_requests WHERE assigned_collector_id=? AND status IN ('verified','completed')").get(id).v||0),paidEarnings:Number(db.prepare("SELECT COALESCE(SUM(pay.collector_payout),0) v FROM payments pay JOIN pickup_requests p ON p.id=pay.pickup_id WHERE p.assigned_collector_id=? AND pay.status='paid'").get(id).v||0),pendingEarnings:Number(db.prepare("SELECT COALESCE(SUM(pay.collector_payout),0) v FROM payments pay JOIN pickup_requests p ON p.id=pay.pickup_id WHERE p.assigned_collector_id=? AND pay.status='pending'").get(id).v||0)};
  const active=db.prepare(`SELECT p.*,u.name customer_name,mc.name material_name FROM pickup_requests p JOIN users u ON u.id=p.customer_id LEFT JOIN material_categories mc ON mc.id=p.category_id WHERE p.assigned_collector_id=? AND p.status NOT IN ('completed','cancelled') ORDER BY p.id DESC`).all(id);
  const available=profile?.verification_status==='verified'&&profile?.availability==='available'?db.prepare(`SELECT p.*,mc.name material_name FROM pickup_requests p LEFT JOIN material_categories mc ON mc.id=p.category_id WHERE p.status='approved' AND p.assigned_collector_id IS NULL ORDER BY p.requested_at LIMIT 20`).all():[];
  res.render('collector/dashboard',{profile,metrics,active,available,currency:setting('payment_currency','UGX')});
});
router.post('/availability',(req,res)=>{const availability=['available','busy','offline'].includes(req.body.availability)?req.body.availability:'offline';db.prepare('UPDATE collector_profiles SET availability=? WHERE user_id=?').run(availability,req.session.user.id);audit(req,'collector_availability_changed','collector_profile',req.session.user.id,{availability});res.redirect('/collector');});
router.post('/jobs/:id/accept',(req,res)=>{try{const p=claimPickup(Number(req.params.id),req.session.user.id);audit(req,'pickup_claimed','pickup',p.id);res.redirect(`/collector/pickups/${p.id}`);}catch(e){res.status(409).render('common/error',{code:409,title:'Job unavailable',message:e.message});}});
router.get('/pickups/:id',(req,res)=>{const pickup=getPickup(req.params.id);if(!pickup||pickup.assigned_collector_id!==req.session.user.id)return res.status(404).render('common/error',{code:404,title:'Pickup not found',message:'This pickup is not assigned to you.'});const history=db.prepare(`SELECT h.*,u.name changed_by_name FROM pickup_status_history h JOIN users u ON u.id=h.changed_by WHERE h.pickup_id=? ORDER BY h.id`).all(pickup.id);const proofs=db.prepare('SELECT id,proof_type,file_name,notes,created_at FROM collection_proofs WHERE pickup_id=? ORDER BY id DESC').all(pickup.id);res.render('collector/pickup-detail',{pickup,history,proofs});});
router.post('/pickups/:id/status',(req,res)=>{const pickup=getPickup(req.params.id);if(!pickup||pickup.assigned_collector_id!==req.session.user.id)return res.status(404).send('Pickup not found');const toStatus=String(req.body.status||'');const allowed=['accepted','en_route','arrived','collected','delivered'];if(!allowed.includes(toStatus))return res.status(400).send('Invalid collector status');const extra={};if(toStatus==='collected'){const w=Number(req.body.collected_weight);if(!(w>0))return res.status(400).send('Collected weight is required');extra.collected_weight=w;}try{const p=transitionPickup({pickupId:pickup.id,toStatus,userId:req.session.user.id,notes:String(req.body.notes||'').slice(0,800),extra});audit(req,'collector_pickup_status','pickup',p.id,{toStatus});res.redirect(`/collector/pickups/${p.id}`);}catch(e){res.status(400).send(e.message)}});
router.post('/pickups/:id/proof',(req,res)=>{
  const pickup=getPickup(req.params.id);if(!pickup||pickup.assigned_collector_id!==req.session.user.id)return res.status(404).send('Pickup not found');const proofType=['collection_photo','material_photo','weight_receipt','delivery_photo','customer_confirmation','other'].includes(req.body.proof_type)?req.body.proof_type:'other';const notes=String(req.body.notes||'').trim().slice(0,1000);let data=null,mime=null,fileName=null;
  if(req.body.file_data){const match=String(req.body.file_data).match(/^data:(image\/(?:jpeg|png|webp)|application\/pdf);base64,([A-Za-z0-9+/=]+)$/);if(!match)return res.status(400).send('Only JPEG, PNG, WebP or PDF proof files are accepted.');mime=match[1];data=Buffer.from(match[2],'base64');if(data.length>2*1024*1024)return res.status(413).send('Proof file is too large. Maximum size is 2 MB.');const ok=mime==='image/jpeg'?data.subarray(0,3).equals(Buffer.from([0xff,0xd8,0xff])):
 mime==='image/png'?data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):
 mime==='image/webp'?data.subarray(0,4).toString()==='RIFF'&&data.subarray(8,12).toString()==='WEBP':
 data.subarray(0,5).toString()==='%PDF-';
 if(!ok)return res.status(400).send('File content does not match declared file type.');
 fileName=require('crypto').randomBytes(14).toString('hex')+({ 'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','application/pdf':'.pdf' }[mime]);}
  if(!data&&!notes)return res.status(400).send('Add a proof file or note.');const info=db.prepare('INSERT INTO collection_proofs(pickup_id,uploaded_by,proof_type,mime_type,file_name,data,notes) VALUES(?,?,?,?,?,?,?)').run(pickup.id,req.session.user.id,proofType,mime,fileName,data,notes);audit(req,'collection_proof_added','collection_proof',info.lastInsertRowid,{pickupId:pickup.id,proofType});res.redirect(`/collector/pickups/${pickup.id}`);
});
router.get('/earnings',(req,res)=>{const id=req.session.user.id;const rows=db.prepare(`SELECT pay.*,p.reference pickup_reference,p.status pickup_status FROM payments pay JOIN pickup_requests p ON p.id=pay.pickup_id WHERE p.assigned_collector_id=? AND pay.collector_payout>0 ORDER BY pay.id DESC`).all(id);const summary={pending:Number(db.prepare("SELECT COALESCE(SUM(pay.collector_payout),0) v FROM payments pay JOIN pickup_requests p ON p.id=pay.pickup_id WHERE p.assigned_collector_id=? AND pay.status='pending'").get(id).v||0),paid:Number(db.prepare("SELECT COALESCE(SUM(pay.collector_payout),0) v FROM payments pay JOIN pickup_requests p ON p.id=pay.pickup_id WHERE p.assigned_collector_id=? AND pay.status='paid'").get(id).v||0)};res.render('collector/earnings',{rows,summary,currency:setting('payment_currency','UGX')});});
router.get('/history',(req,res)=>{const rows=db.prepare(`SELECT p.*,mc.name material_name FROM pickup_requests p LEFT JOIN material_categories mc ON mc.id=p.category_id WHERE p.assigned_collector_id=? ORDER BY p.id DESC`).all(req.session.user.id);res.render('collector/history',{rows});});
module.exports=router;
